source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
#inhibit_all_warnings!

def common
	pod 'WeexSDK'
	pod 'WeexPluginLoader'
	pod 'NatImage', :git => 'https://github.com/ttarigo/nat-media-image.git'
end

target 'WeexNatMediaImage' do
    common
end


